version: "3.9"
services:
  app:
    build: .
    container_name: books-api-container
    environment:
      - FLASK_APP_PORT=8080
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    ports:
      - 8080:8080

  db:
    image: mongo
    container_name: mongodb-container